dataset:
  load_from:
    name: "wandb_file_artifact_name.json"
    version: "latest"
    project: "lm-buddy-prometheus"
    entity: "mozilla-ai"
  text_field: "instruction"

prometheus:
  inference:
    base_url: "http://your.vllm.server:8000/v1"
  tokenizer:
    load_from: "meta-llama/Llama-2-7b-chat-hf"
  max_tokens: 256
  num_answers: 3

tracking:
  name: "lm-buddy-prometheus"
  project: "lm-buddy-examples"
  entity: "mozilla-ai"
