name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: get ruff version
        id: get_ruff_version
        uses: mikefarah/yq@master
        with:
          cmd: yq -oy '.tool.poetry.dev-dependencies.ruff' pyproject.toml

      - name: Install UV, venv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV

      - name: install ruff
        env:
          RUFF_VERSION: ${{ steps.get_ruff_version.outputs.result }}
        run: |
          uv pip install ruff
        continue-on-error: false

      - name: run ruff
        run: | 
          ruff --output-format=github .
        continue-on-error: false
        

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install UV, venv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV

      - name: Install Poetry
        id: poetry
        run: |
          . .venv/bin/activate
          uv pip install poetry
        continue-on-error: false

      - name: Lock Poetry
        run: |
          . .venv/bin/activate
          poetry lock

      - name: Install test dependencies
        run: |
          . .venv/bin/activate
          poetry install
        continue-on-error: true

      - name: Run unit tests
        run: |
          . .venv/bin/activate
          poetry run pytest tests/unit
        continue-on-error: false

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install UV, venv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV

      - name: Install poetry
        id: poetry
        run: |
          uv pip install poetry 
        continue-on-error: false

      - name: Lock Poetry
        run: |
          poetry lock

      - name: Install test dependencies
        run: |
          poetry install
        continue-on-error: true

      - name: Run integration tests
        run: |
          poetry run pytest tests/integration
        continue-on-error: false
