name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  pr-checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Get Ruff Version
        id: get_ruff_version
        uses: mikefarah/yq@master
        with:
          cmd: yq -oy '.tool.poetry.dev-dependencies.ruff' pyproject.toml

      - name: Install uv, venv, Ruff
        id: setup
        env:
          RUFF_VERSION: ${{ steps.get_ruff_version.outputs.result }}
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install ruff
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV
        continue-on-error: false

      - name: Linting with Ruff
        id: linting
        run: | 
          . .venv/bin/activate
          ruff --output-format=github .
        continue-on-error: false

      - name: Install Poetry and Package
        id: install_poetry_and_deps
        run: |
          . .venv/bin/activate
          uv pip install poetry
          poetry lock
          poetry install
        continue-on-error: false

      - name: Unit Tests
        id: unit_tests
        run: |
          . .venv/bin/activate
          poetry run pytest tests/unit
        continue-on-error: false

      - name: Integration Tests
        id: integration_tests
        run: |
          . .venv/bin/activate
          poetry run pytest tests/integration
        continue-on-error: false
