name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  pr-checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Environment
        id: setup
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV
        continue-on-error: false

      - name: Get Ruff Version
        id: get_ruff_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.project.optional-dependencies.ruff[0]' 'pyproject.toml'

      - name: Linting with Ruff
        id: linting
        run: | 
          . .venv/bin/activate
          echo ${{ steps.get_ruff_version.outputs.result }}
          uv pip install ${{ steps.get_ruff_version.outputs.result }}
          ruff --output-format=github .
        continue-on-error: false

      - name: Install Package
        id: install_package
        run: |
          . .venv/bin/activate
          uv pip install "lm_buddy[dev] @ ."
        continue-on-error: false

      - name: Unit Tests
        id: unit_tests
        run: |
          . .venv/bin/activate
          pytest tests/unit
        continue-on-error: false

      - name: Integration Tests
        id: integration_tests
        run: |
          . .venv/bin/activate
          pytest tests/integration
        continue-on-error: false
