name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: get ruff version
        id: get_ruff_version
        uses: mikefarah/yq@master
        with:
          cmd: yq -oy '.tool.poetry.dev-dependencies.ruff' pyproject.toml

      - name: Install UV, venv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          echo "VIRTUAL_ENV=$HOME/.venv" >> $GITHUB_ENV

      - name: install ruff
        env:
          RUFF_VERSION: ${{ steps.get_ruff_version.outputs.result }}
        run: |
          . .venv/bin/activate
          uv pip install ruff
        continue-on-error: false

      - name: Install Poetry and test dependencies
        run: |
          . .venv/bin/activate
          uv pip install poetry
          poetry lock
          poetry install
        continue-on-error: false

      - name: Linting with Ruff
        run: | 
          . .venv/bin/activate
          ruff --output-format=github .
        continue-on-error: true
        
      - name: Unit tests
        id: unit_tests
        run: |
          . .venv/bin/activate
          poetry run pytest tests/unit
        continue-on-error: true

      - name: Integration tests
        run: |
          . .venv/bin/activate
          poetry run pytest tests/integration
        continue-on-error: false
