name: PR Checks

on: [push]

jobs:
  pytest_ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: |
          pip install -r requirements/test.txt
        continue-on-error: true

      - name: Lint with Ruff
        run: |
          ruff --output-format=github .
        continue-on-error: false

      - name: Install full dependencies
        run: |
          pip install ".[test]"
        continue-on-error: true

      - name: Run unit tests
        run: |
          pytest
        continue-on-error: false
