name: Publish to PyPI

on: 
  release:
    types: [created,released]

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Build Distribution
      run: |
        python3 -m pip install build
        python3 -m build
      continue-on-error: false  

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        password: ${{ secrets.PYPI_TEST_KEY }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish to PyPI
      if: github.event_name == 'release' && github.event.action == 'released'
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        password: ${{ secrets.PYPI_KEY }}
